// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ephemeris.proto

package com.abecerra.pvt_ephemeris_client.suplclient.supl;

import com.google.protobuf.*;



public final class Ephemeris {
    private Ephemeris() {
    }

    public static void registerAllExtensions(
            ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            ExtensionRegistry registry) {
        registerAllExtensions(
                (ExtensionRegistryLite) registry);
    }

    public interface GpsTimeProtoOrBuilder extends
            // @@protoc_insertion_point(interface_extends:gnss.GpsTimeProto)
            MessageOrBuilder {

        /**
         * <code>optional int64 nanosecond = 1;</code>
         */
        boolean hasNanosecond();

        /**
         * <code>optional int64 nanosecond = 1;</code>
         */
        long getNanosecond();
    }

    /**
     * Protobuf type {@code gnss.GpsTimeProto}
     */
    public static final class GpsTimeProto extends
            GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:gnss.GpsTimeProto)
            GpsTimeProtoOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use GpsTimeProto.newBuilder() to construct.
        private GpsTimeProto(GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private GpsTimeProto() {
            nanosecond_ = 0L;
        }

        @java.lang.Override
        public final UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private GpsTimeProto(
                CodedInputStream input,
                ExtensionRegistryLite extensionRegistry)
                throws InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            UnknownFieldSet.Builder unknownFields =
                    UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {
                            bitField0_ |= 0x00000001;
                            nanosecond_ = input.readInt64();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final Descriptors.Descriptor
        getDescriptor() {
            return Ephemeris.internal_static_gnss_GpsTimeProto_descriptor;
        }

        @java.lang.Override
        protected GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Ephemeris.internal_static_gnss_GpsTimeProto_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Ephemeris.GpsTimeProto.class, Ephemeris.GpsTimeProto.Builder.class);
        }

        private int bitField0_;
        public static final int NANOSECOND_FIELD_NUMBER = 1;
        private long nanosecond_;

        /**
         * <code>optional int64 nanosecond = 1;</code>
         */
        public boolean hasNanosecond() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>optional int64 nanosecond = 1;</code>
         */
        public long getNanosecond() {
            return nanosecond_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeInt64(1, nanosecond_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += CodedOutputStream
                        .computeInt64Size(1, nanosecond_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Ephemeris.GpsTimeProto)) {
                return super.equals(obj);
            }
            Ephemeris.GpsTimeProto other = (Ephemeris.GpsTimeProto) obj;

            boolean result = true;
            result = result && (hasNanosecond() == other.hasNanosecond());
            if (hasNanosecond()) {
                result = result && (getNanosecond()
                        == other.getNanosecond());
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasNanosecond()) {
                hash = (37 * hash) + NANOSECOND_FIELD_NUMBER;
                hash = (53 * hash) + Internal.hashLong(
                        getNanosecond());
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }



        public static Ephemeris.GpsTimeProto parseFrom(
                ByteString data)
                throws InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Ephemeris.GpsTimeProto parseFrom(
                ByteString data,
                ExtensionRegistryLite extensionRegistry)
                throws InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Ephemeris.GpsTimeProto parseFrom(byte[] data)
                throws InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Ephemeris.GpsTimeProto parseFrom(
                byte[] data,
                ExtensionRegistryLite extensionRegistry)
                throws InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Ephemeris.GpsTimeProto parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Ephemeris.GpsTimeProto parseFrom(
                java.io.InputStream input,
                ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Ephemeris.GpsTimeProto parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static Ephemeris.GpsTimeProto parseDelimitedFrom(
                java.io.InputStream input,
                ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static Ephemeris.GpsTimeProto parseFrom(
                CodedInputStream input)
                throws java.io.IOException {
            return GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Ephemeris.GpsTimeProto parseFrom(
                CodedInputStream input,
                ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(Ephemeris.GpsTimeProto prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code gnss.GpsTimeProto}
         */
        public static final class Builder extends
                GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:gnss.GpsTimeProto)
                Ephemeris.GpsTimeProtoOrBuilder {
            public static final Descriptors.Descriptor
            getDescriptor() {
                return Ephemeris.internal_static_gnss_GpsTimeProto_descriptor;
            }

            @java.lang.Override
            protected GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Ephemeris.internal_static_gnss_GpsTimeProto_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Ephemeris.GpsTimeProto.class, Ephemeris.GpsTimeProto.Builder.class);
            }

            // Construct using Ephemeris.GpsTimeProto.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                nanosecond_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            @java.lang.Override
            public Descriptors.Descriptor
            getDescriptorForType() {
                return Ephemeris.internal_static_gnss_GpsTimeProto_descriptor;
            }

            @java.lang.Override
            public Ephemeris.GpsTimeProto getDefaultInstanceForType() {
                return Ephemeris.GpsTimeProto.getDefaultInstance();
            }

            @java.lang.Override
            public Ephemeris.GpsTimeProto build() {
                Ephemeris.GpsTimeProto result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public Ephemeris.GpsTimeProto buildPartial() {
                Ephemeris.GpsTimeProto result = new Ephemeris.GpsTimeProto(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.nanosecond_ = nanosecond_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return (Builder) super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(Message other) {
                if (other instanceof Ephemeris.GpsTimeProto) {
                    return mergeFrom((Ephemeris.GpsTimeProto) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Ephemeris.GpsTimeProto other) {
                if (other == Ephemeris.GpsTimeProto.getDefaultInstance()) return this;
                if (other.hasNanosecond()) {
                    setNanosecond(other.getNanosecond());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    CodedInputStream input,
                    ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Ephemeris.GpsTimeProto parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (InvalidProtocolBufferException e) {
                    parsedMessage = (Ephemeris.GpsTimeProto) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private long nanosecond_;

            /**
             * <code>optional int64 nanosecond = 1;</code>
             */
            public boolean hasNanosecond() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>optional int64 nanosecond = 1;</code>
             */
            public long getNanosecond() {
                return nanosecond_;
            }

            /**
             * <code>optional int64 nanosecond = 1;</code>
             */
            public Builder setNanosecond(long value) {
                bitField0_ |= 0x00000001;
                nanosecond_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int64 nanosecond = 1;</code>
             */
            public Builder clearNanosecond() {
                bitField0_ = (bitField0_ & ~0x00000001);
                nanosecond_ = 0L;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:gnss.GpsTimeProto)
        }

        // @@protoc_insertion_point(class_scope:gnss.GpsTimeProto)
        private static final Ephemeris.GpsTimeProto DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new Ephemeris.GpsTimeProto();
        }

        public static Ephemeris.GpsTimeProto getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static final Parser<GpsTimeProto>
                PARSER = new AbstractParser<GpsTimeProto>() {
            @java.lang.Override
            public GpsTimeProto parsePartialFrom(
                    CodedInputStream input,
                    ExtensionRegistryLite extensionRegistry)
                    throws InvalidProtocolBufferException {
                return new GpsTimeProto(input, extensionRegistry);
            }
        };

        public static Parser<GpsTimeProto> parser() {
            return PARSER;
        }

        @java.lang.Override
        public Parser<GpsTimeProto> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public Ephemeris.GpsTimeProto getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface IonosphericModelProtoOrBuilder extends
            // @@protoc_insertion_point(interface_extends:gnss.IonosphericModelProto)
            MessageOrBuilder {

        /**
         * <pre>
         * Time used for generating this data (typically, the queried time).
         * </pre>
         *
         * <code>optional .gnss.GpsTimeProto data_time = 1;</code>
         */
        boolean hasDataTime();

        /**
         * <pre>
         * Time used for generating this data (typically, the queried time).
         * </pre>
         *
         * <code>optional .gnss.GpsTimeProto data_time = 1;</code>
         */
        Ephemeris.GpsTimeProto getDataTime();

        /**
         * <pre>
         * Time used for generating this data (typically, the queried time).
         * </pre>
         *
         * <code>optional .gnss.GpsTimeProto data_time = 1;</code>
         */
        Ephemeris.GpsTimeProtoOrBuilder getDataTimeOrBuilder();

        /**
         * <pre>
         * Amplitude parameters
         * </pre>
         *
         * <code>repeated double alpha = 2;</code>
         */
        java.util.List<java.lang.Double> getAlphaList();

        /**
         * <pre>
         * Amplitude parameters
         * </pre>
         *
         * <code>repeated double alpha = 2;</code>
         */
        int getAlphaCount();

        /**
         * <pre>
         * Amplitude parameters
         * </pre>
         *
         * <code>repeated double alpha = 2;</code>
         */
        double getAlpha(int index);

        /**
         * <pre>
         * Period parameters.
         * </pre>
         *
         * <code>repeated double beta = 3;</code>
         */
        java.util.List<java.lang.Double> getBetaList();

        /**
         * <pre>
         * Period parameters.
         * </pre>
         *
         * <code>repeated double beta = 3;</code>
         */
        int getBetaCount();

        /**
         * <pre>
         * Period parameters.
         * </pre>
         *
         * <code>repeated double beta = 3;</code>
         */
        double getBeta(int index);
    }

    /**
     * <pre>
     * Klobuchar Ionospheric Model
     * </pre>
     * <p>
     * Protobuf type {@code gnss.IonosphericModelProto}
     */
    public static final class IonosphericModelProto extends
            GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:gnss.IonosphericModelProto)
            IonosphericModelProtoOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use IonosphericModelProto.newBuilder() to construct.
        private IonosphericModelProto(GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private IonosphericModelProto() {
            alpha_ = java.util.Collections.emptyList();
            beta_ = java.util.Collections.emptyList();
        }

        @java.lang.Override
        public final UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private IonosphericModelProto(
                CodedInputStream input,
                ExtensionRegistryLite extensionRegistry)
                throws InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            UnknownFieldSet.Builder unknownFields =
                    UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            Ephemeris.GpsTimeProto.Builder subBuilder = null;
                            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                                subBuilder = dataTime_.toBuilder();
                            }
                            dataTime_ = input.readMessage(Ephemeris.GpsTimeProto.PARSER, extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(dataTime_);
                                dataTime_ = subBuilder.buildPartial();
                            }
                            bitField0_ |= 0x00000001;
                            break;
                        }
                        case 17: {
                            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                                alpha_ = new java.util.ArrayList<java.lang.Double>();
                                mutable_bitField0_ |= 0x00000002;
                            }
                            alpha_.add(input.readDouble());
                            break;
                        }
                        case 18: {
                            int length = input.readRawVarint32();
                            int limit = input.pushLimit(length);
                            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                                alpha_ = new java.util.ArrayList<java.lang.Double>();
                                mutable_bitField0_ |= 0x00000002;
                            }
                            while (input.getBytesUntilLimit() > 0) {
                                alpha_.add(input.readDouble());
                            }
                            input.popLimit(limit);
                            break;
                        }
                        case 25: {
                            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                                beta_ = new java.util.ArrayList<java.lang.Double>();
                                mutable_bitField0_ |= 0x00000004;
                            }
                            beta_.add(input.readDouble());
                            break;
                        }
                        case 26: {
                            int length = input.readRawVarint32();
                            int limit = input.pushLimit(length);
                            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                                beta_ = new java.util.ArrayList<java.lang.Double>();
                                mutable_bitField0_ |= 0x00000004;
                            }
                            while (input.getBytesUntilLimit() > 0) {
                                beta_.add(input.readDouble());
                            }
                            input.popLimit(limit);
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                    alpha_ = java.util.Collections.unmodifiableList(alpha_);
                }
                if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                    beta_ = java.util.Collections.unmodifiableList(beta_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final Descriptors.Descriptor
        getDescriptor() {
            return Ephemeris.internal_static_gnss_IonosphericModelProto_descriptor;
        }

        @java.lang.Override
        protected GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Ephemeris.internal_static_gnss_IonosphericModelProto_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Ephemeris.IonosphericModelProto.class, Ephemeris.IonosphericModelProto.Builder.class);
        }

        private int bitField0_;
        public static final int DATA_TIME_FIELD_NUMBER = 1;
        private Ephemeris.GpsTimeProto dataTime_;

        /**
         * <pre>
         * Time used for generating this data (typically, the queried time).
         * </pre>
         *
         * <code>optional .gnss.GpsTimeProto data_time = 1;</code>
         */
        public boolean hasDataTime() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <pre>
         * Time used for generating this data (typically, the queried time).
         * </pre>
         *
         * <code>optional .gnss.GpsTimeProto data_time = 1;</code>
         */
        public Ephemeris.GpsTimeProto getDataTime() {
            return dataTime_ == null ? Ephemeris.GpsTimeProto.getDefaultInstance() : dataTime_;
        }

        /**
         * <pre>
         * Time used for generating this data (typically, the queried time).
         * </pre>
         *
         * <code>optional .gnss.GpsTimeProto data_time = 1;</code>
         */
        public Ephemeris.GpsTimeProtoOrBuilder getDataTimeOrBuilder() {
            return dataTime_ == null ? Ephemeris.GpsTimeProto.getDefaultInstance() : dataTime_;
        }

        public static final int ALPHA_FIELD_NUMBER = 2;
        private java.util.List<java.lang.Double> alpha_;

        /**
         * <pre>
         * Amplitude parameters
         * </pre>
         *
         * <code>repeated double alpha = 2;</code>
         */
        public java.util.List<java.lang.Double>
        getAlphaList() {
            return alpha_;
        }

        /**
         * <pre>
         * Amplitude parameters
         * </pre>
         *
         * <code>repeated double alpha = 2;</code>
         */
        public int getAlphaCount() {
            return alpha_.size();
        }

        /**
         * <pre>
         * Amplitude parameters
         * </pre>
         *
         * <code>repeated double alpha = 2;</code>
         */
        public double getAlpha(int index) {
            return alpha_.get(index);
        }

        public static final int BETA_FIELD_NUMBER = 3;
        private java.util.List<java.lang.Double> beta_;

        /**
         * <pre>
         * Period parameters.
         * </pre>
         *
         * <code>repeated double beta = 3;</code>
         */
        public java.util.List<java.lang.Double>
        getBetaList() {
            return beta_;
        }

        /**
         * <pre>
         * Period parameters.
         * </pre>
         *
         * <code>repeated double beta = 3;</code>
         */
        public int getBetaCount() {
            return beta_.size();
        }

        /**
         * <pre>
         * Period parameters.
         * </pre>
         *
         * <code>repeated double beta = 3;</code>
         */
        public double getBeta(int index) {
            return beta_.get(index);
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeMessage(1, getDataTime());
            }
            for (int i = 0; i < alpha_.size(); i++) {
                output.writeDouble(2, alpha_.get(i));
            }
            for (int i = 0; i < beta_.size(); i++) {
                output.writeDouble(3, beta_.get(i));
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += CodedOutputStream
                        .computeMessageSize(1, getDataTime());
            }
            {
                int dataSize = 0;
                dataSize = 8 * getAlphaList().size();
                size += dataSize;
                size += 1 * getAlphaList().size();
            }
            {
                int dataSize = 0;
                dataSize = 8 * getBetaList().size();
                size += dataSize;
                size += 1 * getBetaList().size();
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Ephemeris.IonosphericModelProto)) {
                return super.equals(obj);
            }
            Ephemeris.IonosphericModelProto other = (Ephemeris.IonosphericModelProto) obj;

            boolean result = true;
            result = result && (hasDataTime() == other.hasDataTime());
            if (hasDataTime()) {
                result = result && getDataTime()
                        .equals(other.getDataTime());
            }
            result = result && getAlphaList()
                    .equals(other.getAlphaList());
            result = result && getBetaList()
                    .equals(other.getBetaList());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasDataTime()) {
                hash = (37 * hash) + DATA_TIME_FIELD_NUMBER;
                hash = (53 * hash) + getDataTime().hashCode();
            }
            if (getAlphaCount() > 0) {
                hash = (37 * hash) + ALPHA_FIELD_NUMBER;
                hash = (53 * hash) + getAlphaList().hashCode();
            }
            if (getBetaCount() > 0) {
                hash = (37 * hash) + BETA_FIELD_NUMBER;
                hash = (53 * hash) + getBetaList().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }





        public static Ephemeris.IonosphericModelProto parseFrom(
                ByteString data)
                throws InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Ephemeris.IonosphericModelProto parseFrom(
                ByteString data,
                ExtensionRegistryLite extensionRegistry)
                throws InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Ephemeris.IonosphericModelProto parseFrom(byte[] data)
                throws InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Ephemeris.IonosphericModelProto parseFrom(
                byte[] data,
                ExtensionRegistryLite extensionRegistry)
                throws InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Ephemeris.IonosphericModelProto parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Ephemeris.IonosphericModelProto parseFrom(
                java.io.InputStream input,
                ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Ephemeris.IonosphericModelProto parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static Ephemeris.IonosphericModelProto parseDelimitedFrom(
                java.io.InputStream input,
                ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static Ephemeris.IonosphericModelProto parseFrom(
                CodedInputStream input)
                throws java.io.IOException {
            return GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Ephemeris.IonosphericModelProto parseFrom(
                CodedInputStream input,
                ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(Ephemeris.IonosphericModelProto prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * <pre>
         * Klobuchar Ionospheric Model
         * </pre>
         * <p>
         * Protobuf type {@code gnss.IonosphericModelProto}
         */
        public static final class Builder extends
                GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:gnss.IonosphericModelProto)
                Ephemeris.IonosphericModelProtoOrBuilder {
            public static final Descriptors.Descriptor
            getDescriptor() {
                return Ephemeris.internal_static_gnss_IonosphericModelProto_descriptor;
            }

            @java.lang.Override
            protected GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Ephemeris.internal_static_gnss_IonosphericModelProto_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Ephemeris.IonosphericModelProto.class, Ephemeris.IonosphericModelProto.Builder.class);
            }

            // Construct using Ephemeris.IonosphericModelProto.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                    getDataTimeFieldBuilder();
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                if (dataTimeBuilder_ == null) {
                    dataTime_ = null;
                } else {
                    dataTimeBuilder_.clear();
                }
                bitField0_ = (bitField0_ & ~0x00000001);
                alpha_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000002);
                beta_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000004);
                return this;
            }

            @java.lang.Override
            public Descriptors.Descriptor
            getDescriptorForType() {
                return Ephemeris.internal_static_gnss_IonosphericModelProto_descriptor;
            }

            @java.lang.Override
            public Ephemeris.IonosphericModelProto getDefaultInstanceForType() {
                return Ephemeris.IonosphericModelProto.getDefaultInstance();
            }

            @java.lang.Override
            public Ephemeris.IonosphericModelProto build() {
                Ephemeris.IonosphericModelProto result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public Ephemeris.IonosphericModelProto buildPartial() {
                Ephemeris.IonosphericModelProto result = new Ephemeris.IonosphericModelProto(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                if (dataTimeBuilder_ == null) {
                    result.dataTime_ = dataTime_;
                } else {
                    result.dataTime_ = dataTimeBuilder_.build();
                }
                if (((bitField0_ & 0x00000002) == 0x00000002)) {
                    alpha_ = java.util.Collections.unmodifiableList(alpha_);
                    bitField0_ = (bitField0_ & ~0x00000002);
                }
                result.alpha_ = alpha_;
                if (((bitField0_ & 0x00000004) == 0x00000004)) {
                    beta_ = java.util.Collections.unmodifiableList(beta_);
                    bitField0_ = (bitField0_ & ~0x00000004);
                }
                result.beta_ = beta_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return (Builder) super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(Message other) {
                if (other instanceof Ephemeris.IonosphericModelProto) {
                    return mergeFrom((Ephemeris.IonosphericModelProto) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Ephemeris.IonosphericModelProto other) {
                if (other == Ephemeris.IonosphericModelProto.getDefaultInstance()) return this;
                if (other.hasDataTime()) {
                    mergeDataTime(other.getDataTime());
                }
                if (!other.alpha_.isEmpty()) {
                    if (alpha_.isEmpty()) {
                        alpha_ = other.alpha_;
                        bitField0_ = (bitField0_ & ~0x00000002);
                    } else {
                        ensureAlphaIsMutable();
                        alpha_.addAll(other.alpha_);
                    }
                    onChanged();
                }
                if (!other.beta_.isEmpty()) {
                    if (beta_.isEmpty()) {
                        beta_ = other.beta_;
                        bitField0_ = (bitField0_ & ~0x00000004);
                    } else {
                        ensureBetaIsMutable();
                        beta_.addAll(other.beta_);
                    }
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    CodedInputStream input,
                    ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Ephemeris.IonosphericModelProto parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (InvalidProtocolBufferException e) {
                    parsedMessage = (Ephemeris.IonosphericModelProto) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private Ephemeris.GpsTimeProto dataTime_ = null;
            private SingleFieldBuilderV3<
                    Ephemeris.GpsTimeProto, Ephemeris.GpsTimeProto.Builder, Ephemeris.GpsTimeProtoOrBuilder> dataTimeBuilder_;

            /**
             * <pre>
             * Time used for generating this data (typically, the queried time).
             * </pre>
             *
             * <code>optional .gnss.GpsTimeProto data_time = 1;</code>
             */
            public boolean hasDataTime() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <pre>
             * Time used for generating this data (typically, the queried time).
             * </pre>
             *
             * <code>optional .gnss.GpsTimeProto data_time = 1;</code>
             */
            public Ephemeris.GpsTimeProto getDataTime() {
                if (dataTimeBuilder_ == null) {
                    return dataTime_ == null ? Ephemeris.GpsTimeProto.getDefaultInstance() : dataTime_;
                } else {
                    return dataTimeBuilder_.getMessage();
                }
            }

            /**
             * <pre>
             * Time used for generating this data (typically, the queried time).
             * </pre>
             *
             * <code>optional .gnss.GpsTimeProto data_time = 1;</code>
             */
            public Builder setDataTime(Ephemeris.GpsTimeProto value) {
                if (dataTimeBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    dataTime_ = value;
                    onChanged();
                } else {
                    dataTimeBuilder_.setMessage(value);
                }
                bitField0_ |= 0x00000001;
                return this;
            }

            /**
             * <pre>
             * Time used for generating this data (typically, the queried time).
             * </pre>
             *
             * <code>optional .gnss.GpsTimeProto data_time = 1;</code>
             */
            public Builder setDataTime(
                    Ephemeris.GpsTimeProto.Builder builderForValue) {
                if (dataTimeBuilder_ == null) {
                    dataTime_ = builderForValue.build();
                    onChanged();
                } else {
                    dataTimeBuilder_.setMessage(builderForValue.build());
                }
                bitField0_ |= 0x00000001;
                return this;
            }

            /**
             * <pre>
             * Time used for generating this data (typically, the queried time).
             * </pre>
             *
             * <code>optional .gnss.GpsTimeProto data_time = 1;</code>
             */
            public Builder mergeDataTime(Ephemeris.GpsTimeProto value) {
                if (dataTimeBuilder_ == null) {
                    if (((bitField0_ & 0x00000001) == 0x00000001) &&
                            dataTime_ != null &&
                            dataTime_ != Ephemeris.GpsTimeProto.getDefaultInstance()) {
                        dataTime_ =
                                Ephemeris.GpsTimeProto.newBuilder(dataTime_).mergeFrom(value).buildPartial();
                    } else {
                        dataTime_ = value;
                    }
                    onChanged();
                } else {
                    dataTimeBuilder_.mergeFrom(value);
                }
                bitField0_ |= 0x00000001;
                return this;
            }

            /**
             * <pre>
             * Time used for generating this data (typically, the queried time).
             * </pre>
             *
             * <code>optional .gnss.GpsTimeProto data_time = 1;</code>
             */
            public Builder clearDataTime() {
                if (dataTimeBuilder_ == null) {
                    dataTime_ = null;
                    onChanged();
                } else {
                    dataTimeBuilder_.clear();
                }
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            /**
             * <pre>
             * Time used for generating this data (typically, the queried time).
             * </pre>
             *
             * <code>optional .gnss.GpsTimeProto data_time = 1;</code>
             */
            public Ephemeris.GpsTimeProto.Builder getDataTimeBuilder() {
                bitField0_ |= 0x00000001;
                onChanged();
                return getDataTimeFieldBuilder().getBuilder();
            }

            /**
             * <pre>
             * Time used for generating this data (typically, the queried time).
             * </pre>
             *
             * <code>optional .gnss.GpsTimeProto data_time = 1;</code>
             */
            public Ephemeris.GpsTimeProtoOrBuilder getDataTimeOrBuilder() {
                if (dataTimeBuilder_ != null) {
                    return dataTimeBuilder_.getMessageOrBuilder();
                } else {
                    return dataTime_ == null ?
                            Ephemeris.GpsTimeProto.getDefaultInstance() : dataTime_;
                }
            }

            /**
             * <pre>
             * Time used for generating this data (typically, the queried time).
             * </pre>
             *
             * <code>optional .gnss.GpsTimeProto data_time = 1;</code>
             */
            private SingleFieldBuilderV3<
                    Ephemeris.GpsTimeProto, Ephemeris.GpsTimeProto.Builder, Ephemeris.GpsTimeProtoOrBuilder>
            getDataTimeFieldBuilder() {
                if (dataTimeBuilder_ == null) {
                    dataTimeBuilder_ = new SingleFieldBuilderV3<
                            Ephemeris.GpsTimeProto, Ephemeris.GpsTimeProto.Builder, Ephemeris.GpsTimeProtoOrBuilder>(
                            getDataTime(),
                            getParentForChildren(),
                            isClean());
                    dataTime_ = null;
                }
                return dataTimeBuilder_;
            }

            private java.util.List<java.lang.Double> alpha_ = java.util.Collections.emptyList();

            private void ensureAlphaIsMutable() {
                if (!((bitField0_ & 0x00000002) == 0x00000002)) {
                    alpha_ = new java.util.ArrayList<java.lang.Double>(alpha_);
                    bitField0_ |= 0x00000002;
                }
            }

            /**
             * <pre>
             * Amplitude parameters
             * </pre>
             *
             * <code>repeated double alpha = 2;</code>
             */
            public java.util.List<java.lang.Double>
            getAlphaList() {
                return java.util.Collections.unmodifiableList(alpha_);
            }

            /**
             * <pre>
             * Amplitude parameters
             * </pre>
             *
             * <code>repeated double alpha = 2;</code>
             */
            public int getAlphaCount() {
                return alpha_.size();
            }

            /**
             * <pre>
             * Amplitude parameters
             * </pre>
             *
             * <code>repeated double alpha = 2;</code>
             */
            public double getAlpha(int index) {
                return alpha_.get(index);
            }

            /**
             * <pre>
             * Amplitude parameters
             * </pre>
             *
             * <code>repeated double alpha = 2;</code>
             */
            public Builder setAlpha(
                    int index, double value) {
                ensureAlphaIsMutable();
                alpha_.set(index, value);
                onChanged();
                return this;
            }

            /**
             * <pre>
             * Amplitude parameters
             * </pre>
             *
             * <code>repeated double alpha = 2;</code>
             */
            public Builder addAlpha(double value) {
                ensureAlphaIsMutable();
                alpha_.add(value);
                onChanged();
                return this;
            }

            /**
             * <pre>
             * Amplitude parameters
             * </pre>
             *
             * <code>repeated double alpha = 2;</code>
             */
            public Builder addAllAlpha(
                    java.lang.Iterable<? extends java.lang.Double> values) {
                ensureAlphaIsMutable();
                AbstractMessageLite.Builder.addAll(
                        values, alpha_);
                onChanged();
                return this;
            }

            /**
             * <pre>
             * Amplitude parameters
             * </pre>
             *
             * <code>repeated double alpha = 2;</code>
             */
            public Builder clearAlpha() {
                alpha_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000002);
                onChanged();
                return this;
            }

            private java.util.List<java.lang.Double> beta_ = java.util.Collections.emptyList();

            private void ensureBetaIsMutable() {
                if (!((bitField0_ & 0x00000004) == 0x00000004)) {
                    beta_ = new java.util.ArrayList<java.lang.Double>(beta_);
                    bitField0_ |= 0x00000004;
                }
            }

            /**
             * <pre>
             * Period parameters.
             * </pre>
             *
             * <code>repeated double beta = 3;</code>
             */
            public java.util.List<java.lang.Double>
            getBetaList() {
                return java.util.Collections.unmodifiableList(beta_);
            }

            /**
             * <pre>
             * Period parameters.
             * </pre>
             *
             * <code>repeated double beta = 3;</code>
             */
            public int getBetaCount() {
                return beta_.size();
            }

            /**
             * <pre>
             * Period parameters.
             * </pre>
             *
             * <code>repeated double beta = 3;</code>
             */
            public double getBeta(int index) {
                return beta_.get(index);
            }

            /**
             * <pre>
             * Period parameters.
             * </pre>
             *
             * <code>repeated double beta = 3;</code>
             */
            public Builder setBeta(
                    int index, double value) {
                ensureBetaIsMutable();
                beta_.set(index, value);
                onChanged();
                return this;
            }

            /**
             * <pre>
             * Period parameters.
             * </pre>
             *
             * <code>repeated double beta = 3;</code>
             */
            public Builder addBeta(double value) {
                ensureBetaIsMutable();
                beta_.add(value);
                onChanged();
                return this;
            }

            /**
             * <pre>
             * Period parameters.
             * </pre>
             *
             * <code>repeated double beta = 3;</code>
             */
            public Builder addAllBeta(
                    java.lang.Iterable<? extends java.lang.Double> values) {
                ensureBetaIsMutable();
                AbstractMessageLite.Builder.addAll(
                        values, beta_);
                onChanged();
                return this;
            }

            /**
             * <pre>
             * Period parameters.
             * </pre>
             *
             * <code>repeated double beta = 3;</code>
             */
            public Builder clearBeta() {
                beta_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000004);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:gnss.IonosphericModelProto)
        }

        // @@protoc_insertion_point(class_scope:gnss.IonosphericModelProto)
        private static final Ephemeris.IonosphericModelProto DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new Ephemeris.IonosphericModelProto();
        }

        public static Ephemeris.IonosphericModelProto getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static final Parser<IonosphericModelProto>
                PARSER = new AbstractParser<IonosphericModelProto>() {
            @java.lang.Override
            public IonosphericModelProto parsePartialFrom(
                    CodedInputStream input,
                    ExtensionRegistryLite extensionRegistry)
                    throws InvalidProtocolBufferException {
                return new IonosphericModelProto(input, extensionRegistry);
            }
        };

        public static Parser<IonosphericModelProto> parser() {
            return PARSER;
        }

        @java.lang.Override
        public Parser<IonosphericModelProto> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public Ephemeris.IonosphericModelProto getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final Descriptors.Descriptor
            internal_static_gnss_GpsTimeProto_descriptor;
    private static final
    GeneratedMessageV3.FieldAccessorTable
            internal_static_gnss_GpsTimeProto_fieldAccessorTable;
    private static final Descriptors.Descriptor
            internal_static_gnss_IonosphericModelProto_descriptor;
    private static final
    GeneratedMessageV3.FieldAccessorTable
            internal_static_gnss_IonosphericModelProto_fieldAccessorTable;

    public static Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\017ephemeris.proto\022\004gnss\"\"\n\014GpsTimeProto\022" +
                        "\022\n\nnanosecond\030\001 \001(\003\"[\n\025IonosphericModelP" +
                        "roto\022%\n\tdata_time\030\001 \001(\0132\022.gnss.GpsTimePr" +
                        "oto\022\r\n\005alpha\030\002 \003(\001\022\014\n\004beta\030\003 \003(\001B(\n#com." +
                        "google.location.suplclient.supl\200\001\000"
        };
        Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public ExtensionRegistry assignDescriptors(
                            Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_gnss_GpsTimeProto_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_gnss_GpsTimeProto_fieldAccessorTable = new
                GeneratedMessageV3.FieldAccessorTable(
                internal_static_gnss_GpsTimeProto_descriptor,
                new java.lang.String[]{"Nanosecond",});
        internal_static_gnss_IonosphericModelProto_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_gnss_IonosphericModelProto_fieldAccessorTable = new
                GeneratedMessageV3.FieldAccessorTable(
                internal_static_gnss_IonosphericModelProto_descriptor,
                new java.lang.String[]{"DataTime", "Alpha", "Beta",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
